version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8080:80"
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - storage:/var/www/html/storage
      - vendor:/var/www/html/vendor
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: laravel-db
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: gestion_bibliotheque
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$${MYSQL_ROOT_PASSWORD} | grep 'mysqld is alive'"]
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306" # avoid conflict with local MySQL

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel-pma
    depends_on:
      db:
        condition: service_healthy
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 256M
    ports:
      - "8081:80"

volumes:
  db_data:
  storage:
  vendor:
